name: "package-container"
description: "Composite action to to build a docker image."

inputs:
  IMAGE_NAME:
    required: true
    description: "The name of the image"
  FOLDER_PATH:
    required: true
    description: "The context path to build the docker"
  TOKEN:
    description: "A Github PAT"
    required: true
  USERNAME:
    description: "A Github PAT username"
    required: true
  ORGANIZATION_NAME:
    description: "The organization name"
    required: true

runs:
  using: "composite"
  steps:
    - name: Create a new tag
      id: tag
      uses: anothrNick/github-tag-action@1.69.0
      if: github.ref == 'refs/heads/main'
      env:
        GITHUB_TOKEN: ${{ inputs.TOKEN }}
        WITH_V: "true"
        DEFAULT_BUMP: patch

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{inputs.ORGANIZATION_NAME}}/${{inputs.IMAGE_NAME}}
        tags: |
          type=sha
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ inputs.USERNAME }}
        password: ${{ inputs.TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v5
      if: github.ref != 'refs/heads/main'
      with:
        context: ${{ inputs.FOLDER_PATH }}
        platforms: linux/amd64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Build and push
      uses: docker/build-push-action@v5
      if: github.ref == 'refs/heads/main'
      with:
        context: ${{ inputs.FOLDER_PATH }}
        platforms: linux/amd64
        push: true
        tags: ${{ steps.meta.outputs.tags }},ghcr.io/${{inputs.ORGANIZATION_NAME}}/${{inputs.IMAGE_NAME}}:${{ steps.tag.outputs.new_tag }}
        labels: ${{ steps.meta.outputs.labels }}
