apiVersion: v1
kind: Service
metadata:
  name: notebook
  namespace: kubox
spec:
  selector:
    app: notebook
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
  type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
  name: notebook
  namespace: kubox
  labels:
    app: notebook
spec:
  containers:
    - name: notebook
      image: ghcr.io/kubox-ai/notebook-basic:v0.0.11
      ports:
        - containerPort: 8888
      # env:
      #   - name: JUPYTER_ENABLE_LAB
      #     value: "yes" # Enables JupyterLab
      #   - name: GRANT_SUDO
      #     value: "yes" # Optional, grants sudo access in the container
