apiVersion: v1
kind: Service
metadata:
  name: notebook
  namespace: kubox
spec:
  selector:
    app: notebook
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
  type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
  name: notebook
  namespace: kubox
  labels:
    app: notebook
spec:
  runtimeClassName: nvidia
  containers:
    - name: notebook
      image: ghcr.io/kubox-ai/notebook-gpu:v0.0.11
      ports:
        - containerPort: 8888
      env:
        - name: "NVIDIA_VISIBLE_DEVICES"
          value: "all"
        - name: "NVIDIA_DRIVER_CAPABILITIES"
          value: "compute,utility"
        # - name: "EXTRA_PIP_PACKAGES"
        #   value: "torch torchvision torchaudio boto3 transformers tifffile ml-pyxis opencv-python-headless --upgrade"
